### ISSUE TITLE
Doesn't stack well with great suspender

### ISSUE THREAD

**Issue by atsepkov** [JannesMeyer/TabAttack#20] opened 2016-01-05 20:19 UTC
I have Great Suspender plugin installed, which automatically puts inactive tabs to sleep. Unfortunately it seems like sleeping tabs are ignored. Is it possible to include them? The TabAttack counter on the icon does see them, but the markdown does not. Without being able to see all tabs at once, it's hard for me to curate the list to the tabs I care about when exporting them.

**Comment by atsepkov** [comment] 2016-01-05 20:31
I think the culprit is this logic in `background.js`:

```
// Count highlighted tabs. If >1 only export those.
var highlightedTabs = windows[0].tabs.filter(t => t.highlighted);
if (highlightedTabs.length > 1) {
    windows = [ { tabs: highlightedTabs } ];
}
```

Looks like great suspender works by highlighting tabs it has not put to sleep yet. Can TabAttack add an option to include ALL tabs, not just highlighted ones?

**Comment by JannesMeyer** [comment] 2016-01-10 22:23
Thanks for the bug report! I can reproduce the problem on my machine. I am not sure what is going on, though. It shouldn't be because of highlighted tabs, because those get reset whenever the active tab changes.

I will investigate.

**Comment by JannesMeyer** [comment] 2016-01-10 23:13
I have found the actual cause now. It is happening because I was ignoring all tabs with the `chrome-extension://` URI scheme, so as not to list any instances of the TabAttack extension itself, but I see how that creates problems with things like The Great Suspender.

I could disable that filtering or make it more precise. Anyway, I should be able to fix this soon.

**Comment by JannesMeyer** [comment] 2016-01-10 23:30
I still need to do some testing before I do a release to the Chrome Web Store, but it should be fixed.

**Closed as completed** 2016-01-10 23:30 UTC
